### ISSUE TITLE
Finished French Translation for PixliesProxyCore

### ISSUE THREAD

**Issue by TAMaurice** [PixliesEarth/PixliesCoreV2#35]
Title says it all
[LANG_FRA.txt](https://github.com/PixliesEarth/PixliesCoreV2/files/10311332/LANG_FRA.txt)
I would like @vyketype to look over it, because I'm not as confident in it's accuracy as the german one.

**Comment by vyketype** [comment]
I would change PLAYER_SERVER_CONNECTING to: `"§7Nous essayons de vous rejoindre au serveur §a%SERVER%§7..."`
I would change PLAYER_QUEUE_SETTINGS_COMMAND_PAUSE_DISABLED to: `"§7La queue pour §a%SERVER%§7 est maintenant réactivée."`
I would also change `pausé(e)` to `mis(e) en pause`.
Also, I would put the pronouns in plural (`vous` instead of `tu`).
Make a pull request, and I'll approve it.
